?shipmentType=PICKUP
@startuml

title GET shipmentVariants(PICKIUP)

Front-> Back: <font color=blue><b>GET</font> /web-api/v1/cart/shipmentVariants
Back-> OrderGate: /baskets/{basketId}/lite (проверка наличия корзины)
alt У пользователя есть активная корзина
	Back<--OrderGate: Возвращает ИД корзины пользователя
	Back-> OrderGate: /baskets/{basketId} (получаем корзину)
	Back<--OrderGate: Возвращает полную корзину
	!include https://raw.githubusercontent.com/ViKt0R-K/plantuml/main/cart/leftOrTerritory.puml

	Back->OrderGate: /baskets/{{basket}}/delivery/get-alt-internal-pickup(получаем список магазинов)
	note right: Отправляем в запросе все линии из массивов unallocatedLines и obtainPoints
	Back<--OrderGate: Возвращает список магазинов
	Back->GeoGate: /shops/search (запрос информации по магазинам)
	Back<--GeoGate: Возвращает информацию по магазинам
	Front<-- Back: Возвращает информацию по вариантам получения
else У пользователя нет активной корзины
	Back<--OrderGate: Возвращает "basketExist": false
	Front<-- Back: Возвращает ошибку 400 (bad request)
end


legend left
Поля без изменений
<font color=grey>Поля к удалению</font>
<font color=DodgerBlue>Новые поля</font>
endlegend

@enduml
